### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by irgusite** [EGJ1996/DIS_Project#1]
# Work to do
- [x] Get the 2 group simulation working
- [ ] Get the reynolds working on epuck 
- [ ] Get the PSO results
- [ ] Write the report
# If we have time
- [ ] Optimise the results
- [ ] Prepare the presentation
